apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-discovery
  template:
    metadata:
      labels:
        role: service-discovery
    spec:
      containers:
      - name: service-discovery
        image: acrbootcamp1.azurecr.io/service-discovery:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
      imagePullSecrets:
        - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8761
  selector:
    role: service-discovery
