apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      role: gateway-service
  template:
    metadata:
      labels:
        role: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: acrbootcamp1.azurecr.io/gateway-service:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    role: gateway-service
