apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      role: payment-service
  template:
    metadata:
      labels:
        role: payment-service
    spec:
      containers:
      - name: payment-service
        image: acrbootcamp1.azurecr.io/payment-service:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    role: payment-service
